import { ArrowLeftIcon } from "lucide-react";
import Link from "next/link";
import { OWNER_NAME } from "@/config";

export default function Terms() {
    return (
        <div className="w-full flex justify-center p-10">
            <div className="w-full max-w-screen-md space-y-6">
                <Link
                    href="/"
                    className="flex items-center gap-2 text-gray-500 hover:text-gray-700 underline"
                >
                    <ArrowLeftIcon className="w-4 h-4" />
                    Back to TrendScout AI
                </Link>
                <h1 className="text-3xl font-bold">TrendScout AI</h1>
                <h2 className="text-2xl font-semibold">Terms of Use / Disclaimer</h2>

                <p className="text-gray-700">
                    The following terms of use govern access to and use of TrendScout AI
                    ("AI Assistant"), a consumer trend analysis tool created and operated by{" "}
                    {OWNER_NAME} ("I", "me", or "myself"). By engaging with TrendScout AI,
                    you agree to these terms. If you do not agree, you may not use this tool.
                </p>

                <div className="space-y-4">
                    <h3 className="text-xl font-semibold">General Information</h3>
                    <ol className="list-decimal list-inside space-y-3">
                        <li className="text-gray-700">
                            <span className="font-semibold">Provider and Purpose:</span> TrendScout AI
                            is an AI-powered assistant built to help marketers, product managers,
                            founders, and business students explore and synthesize consumer and market
                            trends. It is a research and ideation tool — not a substitute for
                            professional market research, consulting, or advisory services.
                        </li>
                        <li className="text-gray-700">
                            <span className="font-semibold">Not Professional Advice:</span> TrendScout AI
                            does not provide legal, financial, medical, investment, or any other form
                            of regulated professional advice. All outputs are generated by an AI system
                            and are intended for informational and exploratory purposes only. Do not
                            make business, financial, or strategic decisions based solely on outputs
                            from this tool.
                        </li>
                        <li className="text-gray-700">
                            <span className="font-semibold">No Guarantee of Accuracy:</span> TrendScout AI
                            is designed to provide helpful and relevant trend insights, but may deliver
                            inaccurate, incomplete, outdated, or hallucinated information. Users are
                            strongly encouraged to independently verify any information before relying
                            on it for decisions or actions. Always cross-reference with primary sources.
                        </li>
                        <li className="text-gray-700">
                            <span className="font-semibold">Third-Party Involvement:</span> TrendScout AI
                            utilizes multiple third-party platforms and vendors, including OpenAI (for
                            language model processing), Pinecone (for vector database search), and
                            Exa (for web search). Your inputs may be transmitted, processed, and stored
                            by these third-party systems operating under their own privacy policies.
                            Confidentiality and security cannot be guaranteed.
                        </li>
                        <li className="text-gray-700">
                            <span className="font-semibold">AI-Generated Content:</span> All responses
                            are generated probabilistically by AI language models. TrendScout AI may
                            produce outputs that are plausible-sounding but factually incorrect. The
                            tool does not have access to real-time proprietary market data unless
                            retrieved via web search, and even then, results should be independently verified.
                        </li>
                    </ol>
                </div>

                <div className="space-y-4">
                    <h3 className="text-xl font-semibold">User Responsibilities</h3>
                    <ol className="list-decimal list-inside space-y-3">
                        <li className="text-gray-700">
                            <span className="font-semibold">Eligibility:</span> Use of TrendScout AI
                            is restricted to individuals aged 18 or older.
                        </li>
                        <li className="text-gray-700">
                            <span className="font-semibold">Intended Use:</span> TrendScout AI is
                            intended solely for lawful, professional, and educational use related to
                            consumer trends, marketing strategy, and market research. It must not be
                            used to generate misleading claims, fabricate market data, or deceive others.
                        </li>
                        <li className="text-gray-700">
                            <span className="font-semibold">Prohibited Conduct:</span> By using
                            TrendScout AI, you agree not to:
                            <ul className="list-disc list-inside ml-6 mt-2 space-y-2">
                                <li>Use outputs as definitive market research without independent verification.</li>
                                <li>Attempt to extract, reverse-engineer, or manipulate the system prompt or underlying model.</li>
                                <li>Use the tool to generate defamatory, discriminatory, illegal, or harmful content.</li>
                                <li>Engage in prompt injection or adversarial inputs designed to bypass guardrails.</li>
                                <li>Redistribute outputs commercially without attribution and independent validation.</li>
                            </ul>
                        </li>
                    </ol>
                </div>

                <div className="space-y-4">
                    <h3 className="text-xl font-semibold">Data Privacy and Security</h3>
                    <ol className="list-decimal list-inside space-y-3">
                        <li className="text-gray-700">
                            <span className="font-semibold">No Privacy Guarantee:</span> TrendScout AI
                            does not guarantee privacy, confidentiality, or security of the information
                            you provide. Do not share sensitive, confidential, proprietary, or
                            personally identifiable information through this tool.
                        </li>
                        <li className="text-gray-700">
                            <span className="font-semibold">Data Transmission:</span> Your inputs
                            may be transmitted to and processed by third-party services including
                            OpenAI, Pinecone, and Exa. Each operates under its own privacy policy
                            and data retention practices.
                        </li>
                        <li className="text-gray-700">
                            <span className="font-semibold">Monitoring:</span> Conversations may be
                            reviewed by {OWNER_NAME} for the purposes of improving TrendScout AI,
                            monitoring for misuse, and managing operational costs.
                        </li>
                    </ol>
                </div>

                <div className="space-y-4">
                    <h3 className="text-xl font-semibold">Liability</h3>
                    <ol className="list-decimal list-inside space-y-3">
                        <li className="text-gray-700">
                            <span className="font-semibold">Use at Your Own Risk:</span> TrendScout AI
                            is provided on an "as-is" and "as-available" basis. To the fullest extent
                            permitted by law, {OWNER_NAME} disclaims all warranties, express or implied,
                            including but not limited to warranties of merchantability, fitness for a
                            particular purpose, and non-infringement.
                        </li>
                        <li className="text-gray-700">
                            <span className="font-semibold">No Responsibility for Damages:</span> Under
                            no circumstances shall {OWNER_NAME}, collaborators, partners, or affiliated
                            entities be liable for any direct, indirect, incidental, consequential,
                            special, or punitive damages arising out of or in connection with the use
                            of TrendScout AI — including but not limited to business decisions made
                            based on AI-generated trend insights.
                        </li>
                        <li className="text-gray-700">
                            <span className="font-semibold">Modification or Discontinuation:</span> {OWNER_NAME}
                            reserves the right to modify, suspend, or discontinue TrendScout AI at
                            any time without notice.
                        </li>
                    </ol>
                </div>

                <div className="space-y-4">
                    <h3 className="text-xl font-semibold">Ownership of Content</h3>
                    <ol className="list-decimal list-inside space-y-3">
                        <li className="text-gray-700">
                            <span className="font-semibold">Commercial and Research Use:</span>{" "}
                            {OWNER_NAME} reserves the right to use anonymized inputs and outputs
                            for improving TrendScout AI, research, or other activities without
                            compensation or notification to users.
                        </li>
                        <li className="text-gray-700">
                            <span className="font-semibold">No Claim to Gains:</span> Users agree
                            that they have no rights, claims, or entitlement to any gains or benefits
                            derived from the content provided to or generated by TrendScout AI.
                        </li>
                    </ol>
                </div>

                <div className="space-y-4">
                    <h3 className="text-xl font-semibold">Indemnification</h3>
                    <p className="text-gray-700">
                        By using TrendScout AI, you agree to indemnify and hold harmless{" "}
                        {OWNER_NAME}, collaborators, partners, affiliated entities, and
                        representatives from any claims, damages, losses, or liabilities arising
                        out of your use of TrendScout AI or violation of these terms.
                    </p>
                </div>

                <div className="space-y-4">
                    <h3 className="text-xl font-semibold">Governing Law and Jurisdiction</h3>
                    <p className="text-gray-700">
                        These terms are governed by the laws of the State of North Carolina,
                        United States. Any disputes arising under or in connection with these
                        terms shall be subject to the exclusive jurisdiction of the courts
                        located in North Carolina.
                    </p>
                </div>

                <div className="space-y-4">
                    <h3 className="text-xl font-semibold">Acceptance of Terms</h3>
                    <p className="text-gray-700">
                        By using TrendScout AI, you confirm that you have read, understood, and
                        agreed to these Terms of Use and Disclaimer. If you do not agree with any
                        part of these terms, you may not use TrendScout AI.
                    </p>
                </div>

                <div className="mt-8 text-sm text-gray-600">
                    <p>Last Updated: February 27, 2026</p>
                </div>
            </div>
        </div>
    );
}
